services:
  energy_analytics_diggy:
    build: .
    container_name: energy_web_app_diggy
    environment:
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_CHAT_ID=${TG_CHAT_ID}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - VISICOM_DATA_KEY=${VISICOM_DATA_KEY}
      - VISICOM_TILES_KEY=${VISICOM_TILES_KEY}
    volumes:
      - /home/diggy/energy_analytics/uploads:/code/uploads
      - /home/diggy/energy_analytics/downloads:/code/downloads
      - /home/diggy/energy_analytics/security_logs.db:/code/security_logs.db
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: always
    depends_on:
      - energy_analytics_diggy