version: '3.8'

services:
  energy_analytics_diggy:
    build: .
    container_name: energy_web_app_diggy
    ports:
      - "8002:8002"
    environment:
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
    volumes:
      - .:/code
      - ./uploads:/code/uploads
      - ./downloads:/code/downloads
    restart: always